// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // roadmapSidebar: [{type: 'autogenerated', dirName: 'Roadmaps'}],
  roadmapSidebar: [
    {
      type: 'doc',
      id: 'Roadmaps/introduction',
    },
    // {
    //   type: 'category',
    //   label: 'Foundations',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'Roadmaps/foundations',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Programming',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'Roadmaps/programming',
    //     },
    //   ],
    // },
    {
    type: 'category',
    label: 'DevOps & Cloud',
    items: [
      {
        type: 'category',
        label: 'Infrastructure as Code (Terraform)',
        items: [
          {
            type: 'autogenerated',
            dirName: 'Roadmaps/devops-cloud/infrastructure-as-code-terraform',
          },
        ],
      },
    ],
  },
],
  interviewSidebar: [{type: 'autogenerated', dirName: 'Interview-Questions'}],

};

export default sidebars;
